### ISSUE TITLE
No modulate named "speech_recognition"

### ISSUE THREAD

**Issue by corsair20141** [GGyll/audible-bookmark-extractor#14]
Where does the module "speech_recognition" come from? It is not in PIP or Conda repositories, and I did not see a module included in the code zip.

**Comment by gostak-dd** [comment]
It's just how you import SpeechRecognition which is in requirements.txt

https://pypi.org/project/SpeechRecognition/

**Comment by corsair20141** [comment]
I ran requirements.txt and it did not install SpeechRecognition

**Comment by gostak-dd** [comment]
You ran `pip install -r requirements.txt` ?
I just tried with a fresh virtual environment, works fine

**Comment by corsair20141** [comment]
Yes, in a fresh virtual environment.

**Comment by gostak-dd** [comment]
does it work if you run pip install SpeechRecognition==3.8.1
You might need to update your pip
