### ISSUE TITLE
authenticate prompts for CVF Code: Not sure what that is

### ISSUE THREAD

**Issue by agrohe21** [GGyll/audible-bookmark-extractor#16]
then get error
Traceback (most recent call last):
  File "/home/agrohe/projects/audible-bookmark-extractor/main_file.py", line 626, in <module>
    loop.run_until_complete(audible_obj.main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/agrohe/projects/audible-bookmark-extractor/main_file.py", line 123, in main
    await self.enter_command()
  File "/home/agrohe/projects/audible-bookmark-extractor/main_file.py", line 146, in enter_command
    await getattr(self, f"cmd_{command}", self.invalid_command_callback)(**_kwargs)
  File "/home/agrohe/projects/audible-bookmark-extractor/main_file.py", line 85, in cmd_authenticate
    auth = audible.Authenticator.from_login(
  File "/home/agrohe/projects/audible-bookmark-extractor/env/lib/python3.10/site-packages/audible/auth.py", line 424, in

**Comment by gostak-dd** [comment]
Please provide a better description, when is this happening, what is your full error message?

**Comment by agrohe21** [comment]
This error went away. Thx

**Comment by stefan2904** [comment]
I also get this message when trying to authenticate (after entering email, password, locale).

```
python main_file.py                                 
Audible Bookmark Extractor v1.0
Enter CTRL + C to exit
To download your audiobooks, ensure you are authenticated, then enter download_books
Enter help for a list of commands

No Audible credentials found, please run 'authenticate' to generate them


Enter command: authenticate
Audible Email: <redacted>
Enter Password (will be hidden, press ENTER when done): 
us, ca, uk, au, fr, de, jp, it, in, es

Please enter your locale from the list above: de
CVF Code: 
```


According to the python audible lib: _If 2FA is deactivated and Amazon detects some security risks (too many logins in short times, etc.) you will be asked for a verify code (CVF). In that case, amazon sends you an email or SMS with a code, which you enter here_ ([source](https://audible.readthedocs.io/en/latest/auth/authorization.html#cvf-code))

Unfortunately I haven't received any email from Amazon, so not sure how to proceed.

**Comment by stefan2904** [comment]
It seems that the CVF page changes from time to time, see, e.g., mkb79/Audible#127

Your script is pinning `audible==0.8.2`. The latest release is [0.9.1 from September 2023](https://github.com/mkb79/Audible/releases). Maybe updating solves this issue?

**Comment by stefan2904** [comment]
I quickly tried to manually upgrade to `audible-0.9.1` and that appears to _not_ solve the issue.
