### ISSUE TITLE
"Killed" error when getting bookmarks

### ISSUE THREAD

**Issue by agrohe21** [GGyll/audible-bookmark-extractor#17]
Enter the index number of the book you would like to download, or enter --all for all available books:
15
Getting bookmarks for Impact Players
Killed

**Comment by agrohe21** [comment]
adding print statements into the file, it seems to be when loading the mp3
 audio_book = AudioSegment.from_mp3(
                f"{os.getcwd()}/audiobooks/{title}/{title}.mp3")
                
              I do not see a configurable timeout setting.

**Comment by gostak-dd** [comment]
Interesting, how many bookmarks do you have?

**Comment by agrohe21** [comment]
350. I wrote some code that only read the mp3 for each bookmark one at a
time. I can submit a PR if you are interested?

**Comment by gostak-dd** [comment]
Looks like you are running into memory issues. Yes please submit a PR

**Comment by gostak-dd** [comment]
Closed due to inactivity, unable to debug without further details
