### ISSUE TITLE
Authentication issues with captcha

### ISSUE THREAD

**Issue by mrbusche** [GGyll/audible-bookmark-extractor#4]
Each captcha shows up with what seems like half the picture? (Example below). Are you aware of another way I can auth myself? Or know how to read these tiny captchas?

![image](https://user-images.githubusercontent.com/792378/221748864-fe0214a0-9f85-4a8c-b8a4-8c5e45152015.png)

**Comment by gostak-dd** [comment]
That looks like a full captcha you may have bad luck lol. Are all captchas this unintelligible? Could you post another?

**Comment by mrbusche** [comment]
Tried again tonight and I got a real captcha. I tried 9 or 10 times and kept getting garbage like the one above yesterday. 

Tonight
![image](https://user-images.githubusercontent.com/792378/222019837-7803638a-07c6-4dd7-bb46-8bf1a20256c6.png)

**Comment by gostak-dd** [comment]
Alright thanks, I'll add to the readme that it can take a while to get a readable Captcha
