### ISSUE TITLE
Approval alert then amazon send me a code instead of email

### ISSUE THREAD

**Issue by 0b00101111** [GGyll/audible-bookmark-extractor#5]
Hi there,

Thanks for much for this tool. This can be a great help in me organizing my notes.
I'm facing an issue as this:

```
--- terminal record start ---

Enter Password (will be hidden, press ENTER when done): 
us, ca, uk, au, fr, de, jp, it, in, es

Please enter your locale from the list above: us
Answer for CAPTCHA: z3bztd
Approval alert detected! Amazon sends you a mail.
Please press ENTER when you approve the notification.

--- terminal record end ---
```

So instead of receiving an email to verify, I actually got a code via SMS. Please help.
*This is my first ever issue submitted on Github, please forgive me if I'm not doing it correctly.

Best,
Shuang

**Comment by gostak-dd** [comment]
Thank you for contributing, this has never happened to me. Have you checked your Audible login/security details to opt out of the SMS verification so it goes to email?

**Comment by 0b00101111** [comment]
> Thank you for contributing, this has never happened to me. Have you checked your Audible login/security details to opt out of the SMS verification so it goes to email?

Thanks for your help. I could not find how to change the security options . However, I re-ran the code after I log in to Audible in a browser and it worked.

Again, thanks so much for this tool.
