### ISSUE TITLE
Dependencies installation fails for Python 3.11+

### ISSUE THREAD

**Issue by jeromedalbert** [GGyll/audible-bookmark-extractor#7]
Installation with Python 3.11 fails because requirements.txt currently specifies numpy 1.22.4, which only works for Python 3.8-3.10.

I had to locally change my python version to 3.10.12 as a workaround to make it work.

**Comment by gostak-dd** [comment]
Did updating pandas and numpy to latest versions solve the issue?

**Comment by jeromedalbert** [comment]
It did, see #10 for a fix
