### ISSUE TITLE
get_bookmarks command does not currently work as is, because .wav file is missing

### ISSUE THREAD

**Issue by jeromedalbert** [GGyll/audible-bookmark-extractor#8]
The `get_bookmarks` command is currently expecting a `.wav` file, but `convert_audiobook` only downloads an m4b file and converts it to mp3.

For `get_bookmarks` to work, I had to first manually convert my downloaded m4b with `ffmpeg -i your_file_here.m4b your_file_here.wav`

**Comment by gostak-dd** [comment]
I don't have an Audible subscription currently, could you try loading the file as mp3, alternatively change the line that converts from m4b to mp3 to wav instead and see if that works? Then make a PR?

**Comment by jeromedalbert** [comment]
Loading the file as mp3 worked, which is much better since wav files can be huge. I made #11 for a fix.
